### 1) Basic Array Creation 🍏

Create a 1D NumPy array containing the integers from 10 to 50, inclusive

<details><summary>Useful functions</summary>

```py
numpy.arange(start, stop, step)  # Returns an array of evenly spaced values within a given interval.
```
</details>

In [1]:
import numpy as np

arr = np.arange(10,51,1)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


### 2) Array Arithmetic 🔢

Create two NumPy arrays of shape `(3, 3)`, filled with random integers between 1 and 20

Perform element-wise addition, subtraction, multiplication, and division

<details><summary>Useful functions</summary>

```py
numpy.random.randint(low, high, size)  # Returns an array of random integers from low (inclusive) to high (exclusive)
```
</details>

In [3]:
arr1 = np.random.randint(1,21,size=(3,3))
arr2 = np.random.randint(1,21,size=(3,3))

addition = arr1 + arr2
subtraction = arr1 - arr2
multiplication = arr1 * arr2
division = arr1 / arr2

print("Addition:\n", addition)
print("Subtraction:\n", subtraction)
print("Multiplication:\n", multiplication)
print("Division:\n", division)

Addition:
 [[28 26 15]
 [ 7 29 27]
 [21 10 28]]
Subtraction:
 [[ 12  -2 -11]
 [ -1  -1  -9]
 [-11   4  -8]]
Multiplication:
 [[160 168  26]
 [ 12 210 162]
 [ 80  21 180]]
Division:
 [[2.5        0.85714286 0.15384615]
 [0.75       0.93333333 0.5       ]
 [0.3125     2.33333333 0.55555556]]


In [ ]:
arr1 = 
arr2 = 

addition = arr1 + arr2
subtraction = arr1 - arr2
multiplication = arr1 * arr2
division = arr1 / arr2

print("Addition:\n", addition)
print("Subtraction:\n", subtraction)
print("Multiplication:\n", multiplication)
print("Division:\n", division)

Addition:
 [[ 9  4 17]
 [14 18 17]
 [22 20 10]]
Subtraction:
 [[ -5  -2 -11]
 [ -8  -6 -13]
 [ 10  14   8]]
Multiplication:
 [[14  3 42]
 [33 72 30]
 [96 51  9]]
Division:
 [[0.28571429 0.33333333 0.21428571]
 [0.27272727 0.5        0.13333333]
 [2.66666667 5.66666667 9.        ]]


### 3) Summing the Diagonals 🎲

Create a 5x5 matrix of random integers between 10 and 100

Calculate the sum of both the main diagonal and the anti-diagonal

<details><summary>Useful functions</summary>

```py
numpy.diag(array)    # Extracts the diagonal elements of an array
numpy.fliplr(array)  # Flips the array in the left/right direction
numpy.sum(array)     # Returns the sum of all elements in the array
```
</details>

In [16]:
matrix = np.random.randint(10,101,size=(5,5))

main_diag_sum = np.sum(np.diag(matrix))
anti_diag_sum = np.sum(np.diag(np.fliplr(matrix)))

print("Main diagonal sum:", main_diag_sum)
print("Anti-diagonal sum:", anti_diag_sum)

Main diagonal sum: 284
Anti-diagonal sum: 169


In [ ]:
matrix = np.random.randint(10,101,size=(5,5))

main_diag_sum = matrix.sum(matrix.diagonal)
anti_diag_sum = matrix.sum(np.flip(matrix).diagonal)

print("Main diagonal sum:", main_diag_sum)
print("Anti-diagonal sum:", anti_diag_sum)

Main diagonal sum: 193
Anti-diagonal sum: 221


### 4) Fancy Indexing with Conditions 🔍

Generate a NumPy array of 100 random integers between 1 and 100

Find all elements that are divisible by 3 but not by 5 using array indexing

In [18]:
arr = np.arange(1,101,1)

filtered = arr[(arr % 3 == 0) & (arr % 5 != 0)]

print(filtered)

[ 3  6  9 12 18 21 24 27 33 36 39 42 48 51 54 57 63 66 69 72 78 81 84 87
 93 96 99]


### 5) Flatten, Sort, and Find 📏

Create a 6x6 matrix of random integers

Flatten it into a 1D array, sort the array, and find the 3 largest elements

<details><summary>Useful functions</summary>

```py
numpy.ndarray.ravel(array)  # Returns a flattened array
numpy.sort(array)           # Returns a sorted copy of the array
```
</details>

In [35]:
matrix = np.random.randint(1,1001,size=(6,6))

flattened = np.ravel(matrix)
sorted_array = np.sort(flattened)
largest_3 = sorted_array[-3:]

print("3 largest elements:", largest_3)

3 largest elements: [ 933  998 1000]


### 6) Normalize the Data 📈

Create a NumPy array with 20 random floating-point numbers between 0 and 1

Normalize this data so that the new values range between 0 and 100

> *Hint:* The formula for normalization is: $X_{\text{norm}} = \frac{X - X_{\text{min}}}{X_{\text{max}} - X_{\text{min}}} \times (\text{new-max} - \text{new-min}) + \text{new-min}$

<details><summary>Useful functions</summary>

```py
numpy.random.rand(size)  # Returns an array of random floats in the half-open interval [0.0, 1.0)
```
</details>

In [38]:
arr = np.random.rand(20)
normalized = (arr-np.min(arr))/(np.max(arr)-np.min(arr))*(100-0)+0

print("Normalized array:", normalized)

Normalized array: [ 45.90568197  45.33650616  30.80996129   5.4658108   97.79284789
  80.16644806  35.64869912  57.14298678  53.02788558  36.29938621
  27.52430439  40.35998142 100.          39.93003281  15.95640731
  83.22064462   0.          14.31794631  61.26923701  77.8364972 ]


### 7) Broadcasting and Scaling 📊

Create a 4x5 matrix of random integers between 10 and 100

Subtract the column-wise mean from each element in the matrix

<details><summary>Useful functions</summary>

```py
numpy.ndarray.mean(array, axis)  # Returns the mean of the array along the specified axis
```
</details>

In [42]:
matrix = np.random.randint(10,101,size=(4,5))

column_means = matrix.mean(axis=0)
standardized = matrix - column_means

print("Column-wise mean subtracted:\n", standardized)

Column-wise mean subtracted:
 [[ 21.75  19.25   9.   -28.25   6.75]
 [-21.25 -23.75   9.    33.75  31.75]
 [-33.25  13.25  17.    -0.25 -14.25]
 [ 32.75  -8.75 -35.    -5.25 -24.25]]


### 8) Matrix Multiplication Challenge 🤯

Create two matrices of size 4x3 and 3x5 with random integers

Perform matrix multiplication on them

<details><summary>Useful functions</summary>

```py
numpy.ndarray.dot(array1, array2)  # Returns the dot product of two arrays
```
</details>

In [45]:
matrix1 = np.random.randint(1,1001,size=(4,3))
matrix2 = np.random.randint(1,1001,size=(3,5))

result = np.dot(matrix1, matrix2)

print("Matrix multiplication result:\n", result)
print(result.shape)

Matrix multiplication result:
 [[ 969050  563145  575776  459763  470680]
 [ 479138  343484  263166  218694  254086]
 [1216717 1040888  660251  554663  702889]
 [1352243 1199738  547627  532654  787086]]
(4, 5)


### 9) Find the Peaks 📉

Generate a 1D NumPy array with 20 random integers between 0 and 50

Identify the "peaks" (local maxima) in the array (local maxima)

> *Hint:* compare each element to its neighbors

In [47]:
arr = np.random.randint(0, 51, 20)
print(arr)

is_peak = (arr > np.roll(arr, 1)) & (arr > np.roll(arr, -1))

is_peak[0] = is_peak[-1] = False

print("Peaks:", arr[is_peak])

[15 47 16 20 26 24 31 11 28 16  4 36 42 37 42 17 10  6  8 11]
Peaks: [47 26 31 28 42 42]


### 10) Simulate a Dice Roll 🎲🎲

Simulate rolling two six-sided dice 10,000 times

Count how many times the sum of the two dice equals 7

In [57]:
rolls = np.random.randint(1,7,size=(10000,2))

sums = rolls.sum(axis=1)
sevens = np.sum(sums == 7)

print("Number of times the sum is 7:", sevens)

Number of times the sum is 7: 1612
