In [1]:
# important attributes of the NumPy array: ndarray
import numpy as np

#
a = np.arange(15).reshape(3, 5)
print(f"elements of the array\n {a}")

print(f"ndim of the array\n {a.ndim}")
print(f"shape of the array\n {a.shape}")
print(f"size (total elements) of the array\n {a.size}")
print(f"dtype.name of the array\n {a.dtype.name}")
print(f"itemsize(in bytes) of the array\n {a.itemsize}")
print(f"buffer of the array\n {a.data}")
print(f"type of the array\n {type(a)}")

#
b = np.array([6, 7, 8])
print(f"elements of the array b:\n {b}")
print(f"type array b:\n {type(b)}")

elements of the array
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
ndim of the array
 2
shape of the array
 (3, 5)
size (total elements) of the array
 15
dtype.name of the array
 int32
itemsize(in bytes) of the array
 4
buffer of the array
type of the array
 <class 'numpy.ndarray'>
elements of the array b:
 [6 7 8]
type array b:
 <class 'numpy.ndarray'>


In [20]:
# Array creation
import numpy as np

# from a regular python list or tuple
a = np.array([1, 2, 3]) 
print(a * 10)

#a = np.array(1, 2, 3, 4)    # WRONG

# sequence of sequences is transformed in 2D, ...
b = np.array([(1.5, 2, 3), (4, 5, 6)]) # observation: list of tuples
print(f"sequence of sequences:\n {b}")

# explicit specification of array type
c = np.array([[1, 2], [3, 4]], dtype=complex) # what other values dtype can have?
print(f"explicit specification:\n {c}")

[10 20 30]
sequence of sequences:
 [[1.5 2.  3. ]
 [4.  5.  6. ]]
explicit specification:
 [[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [29]:
# initial placeholder content
a_zeros = np.zeros((3, 4))
a_ones = np.ones((2, 3, 4), dtype=np.int16)
a_empty = np.empty((2, 3))

print(f"Array initialized with all 0's:\n {a_zeros}")

# sequences of numbers
a_seq_int = np.arange(10, 30, 5) # lower to max smallest than upper
a_seq_float = np.arange(0, 2, 0.3)
print(f"array initialized with seq of integers:\n {a_seq_int}")
print(f"array initialized with seq of float:\n {a_seq_float}")

# linear space
a_lin_space = np.linspace(0, 2, 9)
print(f"array initialized with linear space:\n {a_lin_space}")

#
from numpy import pi

x = np.linspace(0, 2 * pi, 10)
f = np.sin(x)
print(f"array initialized with linear space:\n {np.around(x, 3)}")
print(f"sinosidal function of the array:\n {np.around(f, 3)}")

Array initialized with all 0's:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
array initialized with seq of integers:
 [10 15 20 25]
array initialized with seq of float:
 [0.  0.3 0.6 0.9 1.2 1.5 1.8]
array initialized with linear space:
 [0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
array initialized with linear space:
 [0.    0.698 1.396 2.094 2.793 3.491 4.189 4.887 5.585 6.283]
sinosidal function of the array:
 [ 0.     0.643  0.985  0.866  0.342 -0.342 -0.866 -0.985 -0.643 -0.   ]


In [119]:
# Printing arrays
import numpy as np


a = np.arange(6)                    # 1d array
b = np.arange(12).reshape(4, 3)     # 2d array
c = np.arange(24).reshape(2, 3, 4)  # 3d array

print(f"1D array a:\n {a}")
print(f"\n2D array b:\n {b}")
print(f"\n3D array c:\n {b}")

print(f"\nFlat 1D array:\n {np.arange(100)}")
print(f"\nReshaped 2D array:\n {np.arange(100).reshape(10, 10)}")


1D array a:
 [0 1 2 3 4 5]

2D array b:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

3D array c:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

Flat 1D array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]

Reshaped 2D array:
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [43]:
# Basic operations
a = np.array([20, 30, 40, 50])
b = np.arange(4)
c = a - b

print(a)
print(b)
print(c)
print(b**2)
print(10 * np.sin(a))
print(a < 35)
print(a[a < 35])

[20 30 40 50]
[0 1 2 3]
[20 29 38 47]
[0 1 4 9]
[ 9.12945251 -9.88031624  7.4511316  -2.62374854]
[ True  True False False]
[20 30]


In [47]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])
# elementwise product
print(A * B) 

# matrix multiplication
print(A @ B)

# another matrix multiplication
print(A.dot(B))
print(np.dot(A, B))

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


In [53]:
# create instance of default random number generator
rg = np.random.default_rng(1)
a = np.ones((2, 3), dtype=int)

b = rg.random((2, 3))
a *= 3
print(a)

b += a
print(b)

#a += b # not allowed, why?
a = a.astype(float) # separate float array with copy of values of a. The old,int array, is garbage-collected
a += b
print(a)

[[3 3 3]
 [3 3 3]]
[[3.51182162 3.9504637  3.14415961]
 [3.94864945 3.31183145 3.42332645]]
[[6.51182162 6.9504637  6.14415961]
 [6.94864945 6.31183145 6.42332645]]


In [62]:
# upcasting: automatic conversion of arrays to a more general or higher precision data type
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, pi, 3)
print(f"\ndtype.name of b:\n{b.dtype.name}")

c = a + b # integer+float upcast to float array a
print(f"\nc = a + b:\n{np.around(c, 3)}")

d = np.exp(c * 1j) # float upcast to complex
print(f"\nd = e^(c * 1j):\n{np.around(d, 3)}")

print(f"\ndtype of complex var d:\n{d.dtype.name}")



dtype.name of b:
float64

c = a + b:
[1.    2.571 4.142]

d = e^(c * 1j):
[ 0.54 +0.841j -0.841+0.54j  -0.54 -0.841j]

dtype of complex var d:
complex128


In [76]:
# aggregation functions

#a = rg.random((2, 3))
#a = np.arange(9).reshape(3, 3)
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"array a:\n{a}")

print(f"\nsum of array a:\n{a.sum()}")

print(f"\nmax of array a:\n{a.max()}")

print(f"\nmin of array a:\n{a.min()}")

b = np.arange(12).reshape(3, 4)

b.sum(axis=0)     # sum of each column
print(f"\nsum of each column:\n{b.sum()}")

b.min(axis=1)     # min of each row
print(f"\nmin of each row:\n{b.sum()}")

# cumulative sum along each row
print(f"\ncummulative sum along each row:\n{b.cumsum(axis=1)}")

# cumulative sum along each column
print(f"\ncummulative sum along each column:\n{b.cumsum(axis=0)}")

array a:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

sum of array a:
45

max of array a:
9

min of array a:
1

sum of each column:
66

min of each row:
66

cummulative sum along each row:
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]

cummulative sum along each column:
[[ 0  1  2  3]
 [ 4  6  8 10]
 [12 15 18 21]]


In [82]:
# universal functions (ufunc)

B = np.arange(3)
print(f"array B:\n{B}")

print(f"\nexponent of B:\n{np.exp(B)}")
#print(f"exponent of B:\n{np.around(np.exp(B), 3)}")

print(f"\nsquare root of B:\n{np.sqrt(B)}")
#print(f"square root of B:\n{np.around(np.sqrt(B), 3)}")

C = np.array([2., -1., 4.])
print(f"\narray C:\n{C}")

print(f"\nB + C:\n{np.add(B, C)}")

# np.exp(), np.sqrt(), np.add()

array B:
[0 1 2]

exponent of B:
[1.         2.71828183 7.3890561 ]

square root of B:
[0.         1.         1.41421356]

array C:
[ 2. -1.  4.]

B + C:
[2. 0. 6.]


# Indexing, Slicing, and Iterating

## One-dimensional array

In [84]:
import numpy as np

# Create a 1D array with cubes of numbers from 0 to 9
a = np.arange(10)**3
print(f"Array a (cubed values from 0 to 9):\n{a}")

# Access the element at index 2 (cube of 2 = 8)
print(f"\nElement of 'a' at index 2:\n{a[2]}")

# Slice elements from index 2 to 5 (exclusive), i.e., [2, 3, 4] cubes
print(f"\nElements in slice a[2:5] (indices 2 to 4):\n{a[2:5]}")  # lower: 2 (start), upper: 5 (stop, exclusive)

# Slice elements from start to index 6, with a step of 2
print(f"\nElements in slice a[:6:2] (up to index 6, step of 2):\n{a[:6:2]}")  # from start (0), up to (but not including) 6, with step 2

# Reverse the array by using a negative step in the slice
print(f"\nElements in slice a[::-1] (reversed array):\n{a[::-1]}")  # reverse the array by stepping backwards (step = -1)

#c = a[1:4].copy()

array a:
[  0   1   8  27  64 125 216 343 512 729]

element of a on index 2:
8

elements in slice[2:5]:
[ 8 27 64]

element in slice[:6:2]
[ 0  8 64]

element in slice[::-1]
[729 512 343 216 125  64  27   8   1   0]


## Multi-dimensional array

In [85]:
import numpy as np

# Create a 3x4 array (3 rows, 4 columns) with values cubed
a = np.arange(12).reshape(3, 4)**2
print(f"2D array 'a':\n{a}")

# Accessing an element at a specific index [row, column]
print(f"\nElement of 'a' on index [1, 2]:\n{a[1, 2]}")

# Slicing rows and columns (rows 1 to 2, columns 1 to 3)
print(f"\nElements in slice a[1:3, 1:4] (rows 1-2, columns 1-3):\n{a[1:3, 1:4]}")

# Slicing with a step (every second row, every second column)
print(f"\nElements in slice a[:3:2, :4:2] (every second row, every second column):\n{a[:3:2, :4:2]}")

# Reversing the rows
print(f"\nArray 'a' with rows reversed (slice a[::-1]):\n{a[::-1]}")

# Reversing both rows and columns
print(f"\nArray 'a' with both rows and columns reversed (slice a[::-1, ::-1]):\n{a[::-1, ::-1]}")


2D array 'a':
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]

Element of 'a' on index [1, 2]:
36

Elements in slice a[1:3, 1:4] (rows 1-2, columns 1-3):
[[ 25  36  49]
 [ 81 100 121]]

Elements in slice a[:3:2, :4:2] (every second row, every second column):
[[  0   4]
 [ 64 100]]

Array 'a' with rows reversed (slice a[::-1]):
[[ 64  81 100 121]
 [ 16  25  36  49]
 [  0   1   4   9]]

Array 'a' with both rows and columns reversed (slice a[::-1, ::-1]):
[[121 100  81  64]
 [ 49  36  25  16]
 [  9   4   1   0]]


In [86]:
# multi-dimensional array

def f(x, y):
    return 10 * x + y
    
b = np.fromfunction(f, (5, 4), dtype=int)
print(b)
print(b[2, 3])
print(b[0:5, 1])  # each row in the second column of b
print(b[:, 1])    # equivalent to the previous example
print(b[1:3, :])  # each column in the second and third row of b
print(b[-1])   # the last row. Equivalent to b[-1, :]


[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
23
[ 1 11 21 31 41]
[ 1 11 21 31 41]
[[10 11 12 13]
 [20 21 22 23]]
[40 41 42 43]


## Iterating over multi-dimensional array

In [88]:
def f(x, y):
    return 10 * x + y
    
b = np.fromfunction(f, (5, 4), dtype=int)

for element in b:
    print(element)
    
for element in b.flat:
    print(element)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]
0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


# Shape Manipulation

## Changing the shape of an array

In [90]:
a = np.floor(10 * rg.random((3, 4)))
print(a)

print(a.shape)

print(a.ravel()) # flattened array
print(a.reshape(6,2))
print(a.T)
print(a.T.shape)
print(a.shape)


[[3. 7. 3. 4.]
 [1. 4. 2. 2.]
 [7. 2. 4. 9.]]
(3, 4)
[3. 7. 3. 4. 1. 4. 2. 2. 7. 2. 4. 9.]
[[3. 7.]
 [3. 4.]
 [1. 4.]
 [2. 2.]
 [7. 2.]
 [4. 9.]]
[[3. 1. 7.]
 [7. 4. 2.]
 [3. 2. 4.]
 [4. 2. 9.]]
(4, 3)
(3, 4)


In [92]:
# view or copy test

import numpy as np

a = np.arange(6)
b = a.reshape(2, 3)

# Check if b is a view or a copy
if b.base is a:
    print("b is a view of a")
else:
    print("b is a copy of a")


b is a view of a


In [91]:
print(a)
a.resize((2, 6))
print(a)

b = a.reshape(3, -1)

print(b)

print(a)

[[3. 7. 3. 4.]
 [1. 4. 2. 2.]
 [7. 2. 4. 9.]]
[[3. 7. 3. 4. 1. 4.]
 [2. 2. 7. 2. 4. 9.]]
[[3. 7. 3. 4.]
 [1. 4. 2. 2.]
 [7. 2. 4. 9.]]
[[3. 7. 3. 4. 1. 4.]
 [2. 2. 7. 2. 4. 9.]]


## Stacking together different arrays

In [93]:
a = np.floor(10 * rg.random((2, 2)))
print(a)

b = np.floor(10 * rg.random((2, 2)))
print(b)

print(np.vstack((a, b)))
print(np.hstack((a, b)))
print()

a = np.array((1,2,3))
print(a)

b = np.array((2,3,4))
print(b)

cs=np.column_stack((a,b))
print(cs)

[[9. 7.]
 [5. 2.]]
[[1. 9.]
 [5. 1.]]
[[9. 7.]
 [5. 2.]
 [1. 9.]
 [5. 1.]]
[[9. 7. 1. 9.]
 [5. 2. 5. 1.]]

[1 2 3]
[2 3 4]
[[1 2]
 [2 3]
 [3 4]]


In [96]:
import numpy as np

# Create a default random number generator
rg = np.random.default_rng()

# Generate a 2x2 array of random numbers, scale by 10, and apply floor to get integer values
a = np.floor(10 * rg.random((2, 2)))
print(a)  # Print the first 2x2 array 'a'

# Generate another 2x2 array of random numbers, scale by 10, and apply floor to get integer values
b = np.floor(10 * rg.random((2, 2)))
print(b)  # Print the second 2x2 array 'b'

# Vertically stack arrays 'a' and 'b' (combine them along axis 0 - add rows)
print(np.vstack((a, b)))  # Print the result of vertical stacking of arrays 'a' and 'b'

# Horizontally stack arrays 'a' and 'b' (combine them along axis 1 - add columns)
print(np.hstack((a, b)))  # Print the result of horizontal stacking of arrays 'a' and 'b'

print()  #

# Create a 1D array 'a' with elements 1, 2, 3
a = np.array((1, 2, 3))
print(a)  # Print the 1D array 'a'

# Create a 1D array 'b' with elements 2, 3, 4
b = np.array((2, 3, 4))
print(b)  # Print the 1D array 'b'

# Use column_stack to stack the arrays 'a' and 'b' as columns
# This converts 1D arrays into 2D arrays with 3 rows and 2 columns
cs = np.column_stack((a, b))
print(cs)  # Print the result of column stacking 'a' and 'b'

# Create two 1D arrays
c = np.array([1, 2, 3])
d = np.array([4, 5, 6])

# Row stacking: stacks the arrays as rows
#rs = np.row_stack((c, d))  # Equivalent to np.vstack((a, b))
rs = np.vstack((c, d))  # Equivalent to np.vstack((a, b))
print(rs)


[[0. 0.]
 [8. 3.]]
[[2. 3.]
 [0. 5.]]
[[0. 0.]
 [8. 3.]
 [2. 3.]
 [0. 5.]]
[[0. 0. 2. 3.]
 [8. 3. 0. 5.]]

[1 2 3]
[2 3 4]
[[1 2]
 [2 3]
 [3 4]]
[[1 2 3]
 [4 5 6]]


## Splitting one array into several smaller ones

In [97]:
a = np.floor(10 * rg.random((2, 12)))
print(a)

# Split `a` horizontally into 4
print(np.hsplit(a, 4))


[[9. 7. 3. 9. 5. 5. 2. 6. 8. 2. 5. 8.]
 [8. 2. 9. 1. 1. 9. 1. 6. 3. 6. 3. 7.]]
[array([[9., 7., 3.],
       [8., 2., 9.]]), array([[9., 5., 5.],
       [1., 1., 9.]]), array([[2., 6., 8.],
       [1., 6., 3.]]), array([[2., 5., 8.],
       [6., 3., 7.]])]


# Exercises

1. Implement a function that takes a ```matrix``` and two index arrays ```row_indices``` and ```col_indices``` of the same length and returns the ```sum``` of a np.array consisting of the sequence of elements 

```[matrix[row_indices[0], col_indices[0]], ... , matrix[row_indices[N-1], col_indices[N-1]]]```

In [102]:
import numpy as np

def indexed_elements(matrix, row_indices, col_indices):
    # Ensure row_indices and col_indices are the same length
    assert len(row_indices) == len(col_indices), "row_indices and col_indices must have the same length"
    
    # Use np.array with list comprehension to extract the sequence of elements
    return np.array([matrix[row_indices[i], col_indices[i]] for i in range(len(row_indices))]).sum()

# Example usage
matrix = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

row_indices = [0, 1, 2]
col_indices = [1, 2, 0]

result = indexed_elements(matrix, row_indices, col_indices)
print(result)  # Expected output: [20 60 70]


150


In [103]:
import numpy as np

def indexed_elements(matrix, row_indices, col_indices):
    # Use advanced indexing to extract elements directly
    return matrix[row_indices, col_indices].sum()

# Example usage
matrix = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 2, 0])

result = indexed_elements(matrix, row_indices, col_indices)
print(result)  # Expected output: [20 60 70]


150


# NaN

In [104]:
import math
x = math.nan  # NaN in Python


In [105]:
x = float('nan')


In [106]:
import numpy as np
x = np.nan


In [109]:
result = (np.nan == np.nan)  # False
print(result)

result = np.isnan(np.nan)  # True
print(result)


False
True


In [110]:
import numpy as np

# Creating an array with NaN
arr = np.array([1, 2, np.nan, 4])

# Checking for NaN values
print(np.isnan(arr))  # Output: [False False  True False]

# Ignoring NaN values in computations (e.g., computing the mean)
mean_value = np.nanmean(arr)  # np.nanmean ignores NaN as a member
print(mean_value)  # Output: 2.3333333333333335


[False False  True False]
2.3333333333333335


In [112]:
import numpy as np

# Create a NumPy array with stock prices, using np.nan to represent missing values
dates = np.array(['2024-09-01', '2024-09-02', '2024-09-03', '2024-09-04', '2024-09-05'])
stock_prices = np.array([100.5, np.nan, 102.3, 101.8, np.nan])

# Print the initial array with NaN values
print("Initial Stock Prices:")
print(stock_prices)


Initial Stock Prices:
[100.5   nan 102.3 101.8   nan]
