In [ ]:
import numpy as np

In [9]:
a_mul = np.array([[1,2,4], [3,4,5]])
print(a_mul[0])
print(a_mul.shape) # shape 
print(a_mul.ndim) # number of dimenstions
print(a_mul.size)
print(a_mul.dtype)

[1 2 4]
(2, 3)
2
6
int32


In [13]:
a = np.array([[1,2,3],
              [4,"Heasdfa123123123sdfasdfllo",6]])
print(a.dtype)
print(type(a[0][0]))

<U26
<class 'numpy.str_'>


In [16]:
a = np.array([[1,2,3],
              [4,"1",6]], dtype=np.float32)
print(a)
print(a.dtype)
print(type(a[0][0]))
print(a[0][0])
print(a[0,0])

[[1. 2. 3.]
 [4. 1. 6.]]
float32
<class 'numpy.float32'>
1.0
1.0


In [18]:
d = {'1': 'A'}
a = np.array([[1,2,3],
             [4,d,5],
             [5,6,7]])
print(a.dtype)
print(type(a[0][0]))
print(a[0][0])
print(a[0,0])

object
<class 'int'>
1
1


# Arrays

In [22]:
a = np.full((3,3,4), 9)
print(a)

[[[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]

 [[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]

 [[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]]


In [27]:
a = np.zeros((3,3,3), dtype=np.float32)
print(a)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [28]:
a = np.ones((3,3,3))
print(a)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [31]:
a = np.empty((2,2,2))
print(a)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [32]:
x_values = np.arange(0, 1000, 5)
print(x_values)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175
 180 185 190 195 200 205 210 215 220 225 230 235 240 245 250 255 260 265
 270 275 280 285 290 295 300 305 310 315 320 325 330 335 340 345 350 355
 360 365 370 375 380 385 390 395 400 405 410 415 420 425 430 435 440 445
 450 455 460 465 470 475 480 485 490 495 500 505 510 515 520 525 530 535
 540 545 550 555 560 565 570 575 580 585 590 595 600 605 610 615 620 625
 630 635 640 645 650 655 660 665 670 675 680 685 690 695 700 705 710 715
 720 725 730 735 740 745 750 755 760 765 770 775 780 785 790 795 800 805
 810 815 820 825 830 835 840 845 850 855 860 865 870 875 880 885 890 895
 900 905 910 915 920 925 930 935 940 945 950 955 960 965 970 975 980 985
 990 995]


In [33]:
x_values = np.linspace(0, 1000, 33)
print(x_values)

[   0.     31.25   62.5    93.75  125.    156.25  187.5   218.75  250.
  281.25  312.5   343.75  375.    406.25  437.5   468.75  500.    531.25
  562.5   593.75  625.    656.25  687.5   718.75  750.    781.25  812.5
  843.75  875.    906.25  937.5   968.75 1000.  ]


In [34]:
print(np.nan, np.inf)

nan inf


In [39]:
print(np.isnan(np.sqrt(-1)))

True


C:\Users\Andrei\AppData\Local\Temp\ipykernel_61104\1919082837.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.isnan(np.sqrt(-1)))


In [40]:
print(np.array([2])/0)

[inf]


C:\Users\Andrei\AppData\Local\Temp\ipykernel_61104\1846826729.py:1: RuntimeWarning: divide by zero encountered in divide
  print(np.array([2])/0)


In [46]:
a1 = np.arange(1,6,1)
a2 = np.arange(6,10,1)
a2 = np.append(a2, [0])

print(a1)
print(a2)


[1 2 3 4 5]
[6 7 8 9 0]


In [47]:
a1 + a2

array([ 7,  9, 11, 13,  5])

In [48]:
np.cos(a1+a2)

array([ 0.75390225, -0.91113026,  0.0044257 ,  0.90744678,  0.28366219])

# Understanding the `axis` Parameter in NumPy

The `axis` parameter specifies the dimension along which an operation is performed. It determines **which dimension to collapse** during the operation.

---

## General Rule for `axis`
- **`axis=0`**: Operates along the first dimension (e.g., vertical, "columns" in 2D).
- **`axis=1`**: Operates along the second dimension (e.g., horizontal, "rows" in 2D).
- **`axis=n-1`**: Operates along the last dimension in an n-dimensional array.

For an array of shape `(d1, d2, ..., dn)`:
- **`axis=0`**: Collapses the `d1` dimension.
- **`axis=1`**: Collapses the `d2` dimension.
- ...
- **`axis=n-1`**: Collapses the `dn` dimension.

---

## Explanation for Different Dimensions

### 1. **2D Arrays**
Shape: `(rows, columns)`

| Axis  | Operation Scope                  | Example                     |
|-------|----------------------------------|-----------------------------|
| `0`   | Operates along columns (vertical)| Collapse rows → 1 value/col|
| `1`   | Operates along rows (horizontal) | Collapse cols → 1 value/row|

Example:
```python
arr_2d = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])
np.sum(arr_2d, axis=0)  # Output: [12, 15, 18]
np.sum(arr_2d, axis=1)  # Output: [6, 15, 24]


In [64]:
a = np.arange(1,7,1).reshape(2,3)
print(a)
print(np.delete(a, 0, axis=1))

[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]


In [72]:
a = np.arange(1,21,1).reshape(4,5)
print(a)
print(a.reshape((2,10)))
print(a.reshape((20,)))
print(a.reshape(2,2,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


`ravel` => changes in original, `flatten` = copy of original

`resize` => changes in original, `reshape` = copy of original

In [82]:
a = np.linspace(5,100,20)
print(a)
a.resize((2,2,5))
print(a)
print(a.flatten())
print(a.ravel())

var1 = a.ravel()
var1[2] = 100
print(var1)
print(a)

[  5.  10.  15.  20.  25.  30.  35.  40.  45.  50.  55.  60.  65.  70.
  75.  80.  85.  90.  95. 100.]
[[[  5.  10.  15.  20.  25.]
  [ 30.  35.  40.  45.  50.]]

 [[ 55.  60.  65.  70.  75.]
  [ 80.  85.  90.  95. 100.]]]
[  5.  10.  15.  20.  25.  30.  35.  40.  45.  50.  55.  60.  65.  70.
  75.  80.  85.  90.  95. 100.]
[  5.  10.  15.  20.  25.  30.  35.  40.  45.  50.  55.  60.  65.  70.
  75.  80.  85.  90.  95. 100.]
[  5.  10. 100.  20.  25.  30.  35.  40.  45.  50.  55.  60.  65.  70.
  75.  80.  85.  90.  95. 100.]
[[[  5.  10. 100.  20.  25.]
  [ 30.  35.  40.  45.  50.]]

 [[ 55.  60.  65.  70.  75.]
  [ 80.  85.  90.  95. 100.]]]


In [83]:
var = [v for v in a.flat]
print(var)

[5.0, 10.0, 100.0, 20.0, 25.0, 30.0, 35.0, 40.0, 45.0, 50.0, 55.0, 60.0, 65.0, 70.0, 75.0, 80.0, 85.0, 90.0, 95.0, 100.0]


In [87]:
a = np.arange(1,7,1).reshape(3,2)
print(a.transpose())
print(a.T)
print(a.T.shape)
print(a.swapaxes(0,1))

[[1 3 5]
 [2 4 6]]
[[1 3 5]
 [2 4 6]]
(2, 3)
[[1 3 5]
 [2 4 6]]


In [94]:
a1 = np.arange(1,11,1).reshape(2,5)
a2 = np.arange(11,21,1).reshape(2,5)

a = np.concatenate((a1,a2), axis=1)

print(np.split(a, 2, axis=1))


[array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]]), array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])]


In [99]:
a = np.arange(1,25,1).reshape(4,6)
print(a)

print(a.min())
print(a.max())
print(a.mean())
print(a.std())
print(a.sum())
print(np.median(a))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
1
24
12.5
6.922186552431729
300
12.5


In [102]:
number = np.random.randint(100)
print(number)

73


In [105]:
numbers = np.random.randint(2,4, size=(2,3,4))
print(numbers)

[[[3 3 2 2]
  [2 3 2 2]
  [3 2 2 3]]

 [[3 3 3 3]
  [3 2 2 2]
  [3 3 3 2]]]


In [110]:
numbers = np.random.binomial(10, p=0.5, size=(5,10))
numbers[numbers < 5] = 0
numbers[numbers >= 5] = 1
print(numbers)

[[0 1 1 1 1 1 1 1 1 1]
 [0 1 1 1 1 1 1 0 1 1]
 [1 1 1 0 1 0 1 0 0 1]
 [1 1 1 1 0 0 1 0 0 1]
 [1 0 1 0 0 1 1 0 1 1]]


In [111]:
numbers = np.random.choice([1,2,3,4444,5,5,555], size = (5,10))
print(numbers)

[[   5    5    2    5  555 4444    5 4444    5 4444]
 [   2    5    1    2    5  555    1    3    5 4444]
 [ 555  555    1    3 4444  555  555    5    1  555]
 [   5    5 4444    5    2    2    1    1  555    5]
 [   3 4444    2  555    5    1 4444    1    5  555]]
